---
- name: PLAY demo surcharge vars
  hosts: all

  vars:
    my_var: "plouf"

  tasks:
    - name: traitement d'une variable
      ansible.builtin.debug:
        msg: "Pour le serveur {{ inventory_hostname }} la variable my_var est : {{ my_var }}"