---
- name: PLAY de demo premier playbook
  hosts: all
  #gather_facts: true

  tasks:

    - name: Utilisation du module user
      ansible.builtin.user:
        name: james
        shell: /bin/bash

    - name: Utilisation d'un second module
      ansible.builtin.shell: date