# CF TP2 Variables_facts

- name: PLAY requirements - variables et facts
  hosts: common
  
  # Bloc vars : déclaration de variables dans le playbook
  vars:
    
    # variable de type liste
    liste_packages:
      - vim
      - nano
      - curl

    # variable de type liste
    #liste_user:
    #  - formation
    #  - dev01
    #  - deploy01

    liste_user:
      formation:
        state: present
        create_home: true
        shell: /bin/bash
        comment: User formation
        password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          65303239653235393966366433623830643333306333626437333336343661346530323961333032
          6166323935303962623636646134326665376130386338640a653239326364633663363632626238
          36333831306162356133346663656134626665373362666634386634343161366437646262393362
          3831356561333430350a653162656237366531326531343865313639623530373862396538393837
          6134
      dev01:
        state: present
        create_home: true
        shell: /bin/bash
      deploy01:
        state: absent
      deploy2:

  tasks:
    # Exercice 1
    - name: "Utilisation des facts via module : debug"
      ansible.builtin.debug:
        #msg: "La distri est un {{ ansible_distribution }}"
        #msg: 
        #  - "La distri est un {{ ansible_facts['distribution'] }}"
        #  - "La version majeure est : {{ ansible_facts['distribution_major_version'] }}"
        #  - "Executable python : {{ ansible_facts['python']['executable'] }}"
        #msg: "Executable python : {{ ansible_python.executable }}"
        #var: ansible_facts['python']
        var: liste_user
        verbosity: 0

    # Exercice 2
    - name: "Installation de packages"
      ansible.builtin.package:
        # Injection du contenu de la variable liste_package => liste d'éléments
        name: "{{ liste_packages }}"
        state: present
      become: true


    # Exercice 3
    #- name: "Creation des utilisateurs"
    #  ansible.builtin.user:
    #    # Injection d'un élément : item de la variable liste_user
    #    name: "{{ item }}"
    #  # Utilisation de la fonction loop pour traiter les éléments d'une liste
    #  loop: "{{ liste_user }}"
    #  become: true

    # Exercice 4 et 5
    - name: "Creation des utilisateurs"  
      ansible.builtin.user:
        # Injection des éléments d'un dictionnaire : item.key et item.value
        name: "{{ item.key }}"
        # Utilisation d'un filter pour positionner une valeur par defaut si item.value.state est vide
        state: "{{ item.value.state | default('absent') }}"
        create_home: "{{ item.value.create_home | default('yes') }}"
        # Utilisation d'un filter default avec omit pour ne pas traiter le parametre shell (/!\ les valeur par defaut prevues par le module sont conservées)
        shell: "{{ item.value.shell | default(omit) }}"
        comment: "{{ item.value.comment | default(omit) }}"
        password: "{{ item.value.password | password_hash('sha512','ndqui7Ywog6/hk') if (item.value.password is defined) else omit}}"
        update_password: "{{ password_strategie | default('on_create') }}"
        remove: yes
      # Utilisation de la fonction loop pour traiter les éléments d'une liste
      loop: "{{ liste_user | dict2items}}"
      become: true
      no_log: true
      # Utilisation register : on stocke l'output d'un module dans une variable pour utilisation future
      register: user_result

    - name: "Analyse du register user_result via debug"
      ansible.builtin.debug:
        #var: item
        msg: 
          - " Create home : {{ item.invocation.module_args.create_home }}"
          - " Home dir : {{ item.home }}"
          - "Name: {{ item.name }}"
      loop: "{{ user_result.results }}"
      when: item.state == 'present'

    - name: "Ajout d'un fichier pour les users"
      ansible.builtin.copy:
        src: "./info.txt"
        dest: "/home/{{ item.key }}"
        owner: "{{ item.key }}"
        group: "{{ item.key }}"
        mode: "0640"
      loop:
        - "{{ liste_user | dict2items }}"
      become: true
      when: 
        - item.value.state is defined
        - item.value.state == 'present'
