- name: modifie le serveradmin
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: "ServerAdmin {{ admin }}"
    validate: httpd -t -f %s
  notify:
    - restart apache