---
# tasks file for ansible_role_apache
- name: 'INIT | VARIABLES | Load OS family vars file'
  include_vars: "{{ role_path }}/vars/{{ ansible_os_family | lower }}.yaml"

- name: 'INSTALL | Manage OS family installation tasks'
  include_tasks: "{{ role_path }}/tasks/install_{{ ansible_os_family | lower }}.yaml"


- name: 'CONFIGURE | Manage Os family configuration tasks'
  include_tasks: "{{ role_path }}/tasks/configure_{{ ansible_os_family | lower }}.yaml"